version: "3.3"

services:
  server:
    build:
      context: .
    restart: always
    volumes:
      - $DIRECTORY_TO_SHARE:/resources
    ports:
      - "127.0.0.1:${SERVER_PORT}:3000"
    environment:
      - D_USERNAME=$D_USERNAME
      - D_PASSWORD=$D_PASSWORD
